-- Add up migration script here
CREATE TABLE "Project" (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ProjectUser" (
  id INTEGER PRIMARY KEY,
  user_id INTEGER,
  project_id INTEGER,
  FOREIGN KEY (project_id) REFERENCES Project(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE SET NULL
);
